@startuml
Client->SP:重新登录\n(只退出SP后，IDP没有没退出)
SP->SecurityContextPersistenceFilter:下一个filter
SecurityContextPersistenceFilter -> SecurityContextPersistenceFilter:doFilter 获取context,\n如果context为空\n则创建新的context
SecurityContextPersistenceFilter->AnonymousAuthenticationFilter:匿名认证filter
AnonymousAuthenticationFilter->AnonymousAuthenticationFilter:createAuthentication(request)\n如果认证信息为空，则创建匿名的认证信息体
AnonymousAuthenticationFilter->SessionManagementFilter:会话管理filter
SessionManagementFilter->SessionManagementFilter:检测sessionId是否有效\n(无效:因为session之前登出过)
SessionManagementFilter->ExceptionTranslationFilter:异常filter
ExceptionTranslationFilter->FilterSecurityInterceptor:安全filter
FilterSecurityInterceptor->FilterSecurityInterceptor:invoke(fi)
FilterSecurityInterceptor->FilterSecurityInterceptor:beforeInvocation(fi)
FilterSecurityInterceptor->AffirmativeBased:decide()判断是否可以访问
AffirmativeBased->ExceptionTranslationFilter:无权限，捕获异常
ExceptionTranslationFilter->ExceptionTranslationFilter:sendStartAuthentication
ExceptionTranslationFilter->ExceptionTranslationFilter:handleSpringSecurityException
ExceptionTranslationFilter->ConfigurableSAMLEntryPoint:commence 开始处理AutheRequest
ConfigurableSAMLEntryPoint->ConfigurableSAMLProcessor:sendMessage 给client响应AutheRequest
ConfigurableSAMLProcessor->Client:返回SAMLRequest，
Client->IDP:将Request提交到(带上去登的idpSessionId)idp的/SingleSignOnService
IDP->Client:idpSessionId校验idp登录还有效，\n直接返回验证后的授权信息；\n而不是让client重定向到填写登录页面
Client->SAMLProcessingFilter:attemptAuthentication()
SAMLProcessingFilter->ProxiedSAMLContextProviderLB:
ProxiedSAMLContextProviderLB->ConfigurableSAMLProcessor:retrieveMessage 检索认证信息
ProviderManager->RoleSAMLAuthenticationProvider:authenticate
RoleSAMLAuthenticationProvider->WebSSOProfileConsumerImpl:processAuthenticationResponse 处理idp的响应信息，各种验证，并生成凭据
WebSSOProfileConsumerImpl->SAMLProcessingFilter:返回认证成功信息
SAMLProcessingFilter->SAMLProcessingFilter:successfulAuthentication context设setAuthentication
SAMLProcessingFilter->SavedRequestAwareAuthenticationSuccessHandler:
SavedRequestAwareAuthenticationSuccessHandler->DefaultRedirectStrategy:sendRedirect 向client发送重定向地址
@enduml
